##
##  Makefile -- Build procedure for sample numberplace Apache module
##  Autogenerated via ``apxs -n numberplace -g''.
##

builddir=.
top_srcdir=/usr/share/apache2
top_builddir=/usr/share/apache2
include /usr/share/apache2/build/special.mk

SH_LIBS=-L/usr/lib64 -lstdc++ -lpthread
CXX=g++
CXXFLAGS=-O2 -g -Wall

#   the used tools
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules-yes

#   cleanup
clean:
	-rm -f mod_numberplace.o mod_numberplace.lo mod_numberplace.slo mod_numberplace.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/numberplace

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

